### ISSUE TITLE
Mark Message must come before Move Message for it to work properly

### ISSUE THREAD

**Issue by sanmarcos** [JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#120] opened 2016-02-11 22:09 UTC
Mark Message as must come before Move Message to.

If you don't do this and move the message and then try to mark it as Read, it doesn't work (message gets moved but not mark as read!)

See http://www.dovecot.org/list/dovecot/2012-July/084414.html

Perhaps you could warn users about this, or actually add support for using the direct ":flags" fileinto argument if you want to set the applied flags explicitly, without depending on any addflag,setflag,removeflag commands

See https://tools.ietf.org/html/rfc5232#section-5

**Comment by JohnDoh** [comment] 2016-02-12 07:32
dupe of #113

**Closed by JohnDoh** 2016-02-12 07:32 UTC
